---
- - "+5 Dexterity Vest"
  - :normal
  - 10
  - 20
- - Aged Brie
  - :vintage
  - 2
  - 0
- - Elixir of the Mongoose
  - :normal
  - 5
  - 7
- - Sulfuras, Hand of Ragnaros
  - :enduring
  - 0
  - 80
- - Backstage passes to a TAFKAL80ETC concert
  - :fleeting
  - 15
  - 20
- - Conjured Mana Cake
  - :conjured
  - 3
  - 6

